---
# handlers file for tool
- name: Start and enable MySQL service
  service:
    name: "{{ mysql_vars[ansible_os_family]['mysql_service'] }}"
    state: started
    enabled: true
    
- name: Restart MySQL
  service:
    name: "{{ mysql_vars[ansible_os_family]['mysql_service'] }}"
    state: restarted