---
- name: Manage MySQL Database
  hosts: aws_ec2
  become: true
  vars:
    db_user: mysqluser
    db_pass: user1234
    db_name: school
    table_name: student   
  tasks:
     - name: Delete the table
       community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        login_db: "{{ db_name }}"
        query: "DROP TABLE IF EXISTS {{ table_name }};"   
  
