---

#retry_join: "{{ groups['tag_DB_mysql'] | map('extract', hostvars, ['private_ip_address']) | list }}"

#- name: Debug private IPs for retry_join
# debug:
#   msg: "{{ retry_join }}"

- name: Creating MySQL user (medium_post)
  community.mysql.mysql_user:  
    name: "{{ db_user }}"  
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: "%"
    #host: "{{ hostvars[groups['tag_DB_mysql'][0]].private_ip_address }}"
    state: present
    column_case_sensitive: false  

- name: Creating medium_db
  community.mysql.mysql_db:  
    name: "{{ db_name }}"
    state: present
